"""Build a tunnel-focused quadtree grid with Gridgen and export to FloPy/MODFLOW 6.

Goal:
- Fine cells close to the tunnel (0-10 m from tunnel boundary)
- Gradually coarser cells farther away
- Keep workflow fully compatible with FloPy and MODFLOW 6 (DISV)

Requirements:
- A tunnel polygon shapefile at tunneldata/tunnel.shp
- Gridgen executable available (default: gridgen_x64)
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import shutil
import sys

import flopy
import geopandas as gpd
import matplotlib.pyplot as plt
import numpy as np
import pyvista as pv
from flopy.export.vtk import Vtk
from flopy.utils.gridgen import Gridgen
from shapely.geometry.base import BaseGeometry


@dataclass
class TunnelGridConfig:
    root: Path = Path(__file__).resolve().parent

    # Input tunnel polygon (generated by tunnel.py in this workspace).
    tunnel_shapefile: Path = Path("tunneldata/tunnel.shp")

    # Gridgen settings.
    gridgen_exe: str = "gridgen_x64"
    gridgen_workspace_name: str = "conceptm_gridgen"

    # Domain and base structured grid used as quadtree parent grid.
    x_len: float = 100.0
    y_len: float = 100.0
    z_len: float = 100.0
    nlay: int = 10
    nrow_base: int = 10
    ncol_base: int = 10
    top: float = 0.0

    # Enhanced refinement setup: finer cells around tunnel, still fast.
    # Level 3 = very fine within 10 m, level 2 = fine within 20 m.
    refinement_distances_m: tuple[float, ...] = (10.0, 20.0, 35.0)
    refinement_levels: tuple[int, ...] = (3, 2, 1)


    # Output simulation proving DISV compatibility.
    sim_name: str = "conceptm_grid"
    sim_workspace_name: str = "conceptm_grid_workspace"

    # Plotting controls.
    save_pyvista_screenshot: bool = True
    show_pyvista_interactive: bool = True
    plot_refinement_zones_2d: bool = False

    @property
    def tunnel_path(self) -> Path:
        return self.root / self.tunnel_shapefile

    @property
    def gridgen_workspace(self) -> Path:
        return self.root / self.gridgen_workspace_name

    @property
    def sim_workspace(self) -> Path:
        return self.root / self.sim_workspace_name

    @property
    def images_dir(self) -> Path:
        return self.root / "images"

    @property
    def delr(self) -> float:
        return self.x_len / self.ncol_base

    @property
    def delc(self) -> float:
        return self.y_len / self.nrow_base

    @property
    def botm(self) -> np.ndarray:
        return np.linspace(-self.z_len / self.nlay, -self.z_len, self.nlay)


def load_tunnel_geometry(cfg: TunnelGridConfig) -> BaseGeometry:
    if not cfg.tunnel_path.exists():
        raise FileNotFoundError(
            f"Tunnel shapefile not found: {cfg.tunnel_path}. "
            "Create it first with tunnel.py."
        )

    gdf = gpd.read_file(cfg.tunnel_path)
    if gdf.empty:
        raise ValueError(f"Tunnel shapefile is empty: {cfg.tunnel_path}")

    if hasattr(gdf.geometry, "union_all"):
        geom = gdf.geometry.union_all()
    else:
        geom = gdf.geometry.unary_union
    if geom.is_empty:
        raise ValueError("Tunnel geometry is empty after unary_union.")

    return geom


def load_tunnel_metadata(cfg: TunnelGridConfig) -> tuple[float, float]:
    """Return tunnel center depth and radius from shapefile attributes."""
    gdf = gpd.read_file(cfg.tunnel_path)
    depth_m = float(gdf["depth_m"].iloc[0]) if "depth_m" in gdf.columns else cfg.z_len * 0.5
    radius_m = float(gdf["radius_m"].iloc[0]) if "radius_m" in gdf.columns else 4.0
    return depth_m, radius_m


def resolve_gridgen_executable(exe_name_or_path: str) -> str:
    """Resolve Gridgen executable name/path to something callable by FloPy."""
    candidate = Path(exe_name_or_path)
    if candidate.exists():
        return str(candidate)

    # Common case: executable lives in the active virtual environment Scripts folder.
    py_dir = Path(sys.executable).resolve().parent
    local_candidates = [
        py_dir / exe_name_or_path,
        py_dir / f"{exe_name_or_path}.exe",
    ]
    for local_candidate in local_candidates:
        if local_candidate.exists():
            return str(local_candidate)

    in_path = shutil.which(exe_name_or_path)
    if in_path is not None:
        return in_path

    in_path_exe = shutil.which(f"{exe_name_or_path}.exe")
    if in_path_exe is not None:
        return in_path_exe

    raise FileNotFoundError(
        "Gridgen executable was not found. "
        "Set TunnelGridConfig.gridgen_exe to an absolute path, "
        "or add Gridgen to PATH."
    )


def build_base_modelgrid(cfg: TunnelGridConfig):
    sim_base = flopy.mf6.MFSimulation(sim_name="base", sim_ws=str(cfg.root / "_tmp_base"))
    gwf_base = flopy.mf6.ModflowGwf(sim_base, modelname="base")
    flopy.mf6.ModflowGwfdis(
        gwf_base,
        nlay=cfg.nlay,
        nrow=cfg.nrow_base,
        ncol=cfg.ncol_base,
        delr=cfg.delr,
        delc=cfg.delc,
        top=cfg.top,
        botm=cfg.botm,
        xorigin=0.0,
        yorigin=0.0,
    )
    return gwf_base.modelgrid


def build_refined_gridprops(cfg: TunnelGridConfig) -> dict:
    if len(cfg.refinement_distances_m) != len(cfg.refinement_levels):
        raise ValueError("refinement_distances_m and refinement_levels must have same length.")

    tunnel_geom = load_tunnel_geometry(cfg)

    cfg.gridgen_workspace.mkdir(parents=True, exist_ok=True)
    modelgrid = build_base_modelgrid(cfg)
    gridgen_exe = resolve_gridgen_executable(cfg.gridgen_exe)
    g = Gridgen(modelgrid, model_ws=str(cfg.gridgen_workspace), exe_name=gridgen_exe)

    # DISV requires same ncpl in each layer, so refinement must be applied to all layers.
    layers = list(range(cfg.nlay))

    # Add outer (coarse) first and inner (fine) last.
    refinement_pairs = list(zip(cfg.refinement_distances_m, cfg.refinement_levels))
    for distance_m, level in sorted(refinement_pairs, key=lambda x: x[0], reverse=True):
        feature = [tunnel_geom.buffer(distance_m)]
        g.add_refinement_features(feature, "polygon", int(level), layers)

    g.build(verbose=False)
    return g.get_gridprops_disv()


def _build_refinement_rings(
    tunnel_geom: BaseGeometry,
    distances_m: tuple[float, ...],
    levels: tuple[int, ...],
) -> list[tuple[BaseGeometry, float, int]]:
    """Create effective ring geometries used by nested Gridgen refinement."""
    rings: list[tuple[BaseGeometry, float, int]] = []
    prev_buffer = tunnel_geom
    for dist, level in sorted(zip(distances_m, levels), key=lambda x: x[0]):
        current_buffer = tunnel_geom.buffer(dist)
        ring = current_buffer.difference(prev_buffer)
        rings.append((ring, float(dist), int(level)))
        prev_buffer = current_buffer
    return rings


def plot_refinement_setup(cfg: TunnelGridConfig, tunnel_geom: BaseGeometry) -> Path:
    """Plot tunnel and refinement rings so the setup is easy to inspect."""
    cfg.images_dir.mkdir(parents=True, exist_ok=True)
    out_png = cfg.images_dir / "conceptm_refinement_zones.png"

    rings = _build_refinement_rings(
        tunnel_geom,
        cfg.refinement_distances_m,
        cfg.refinement_levels,
    )

    fig, ax = plt.subplots(figsize=(9, 7))

    colors = plt.cm.YlOrRd(np.linspace(0.35, 0.95, len(rings)))
    for (ring, dist, level), color in zip(rings[::-1], colors[::-1]):
        gpd.GeoSeries([ring]).plot(ax=ax, facecolor=color, edgecolor="black", alpha=0.45)
        rp = ring.representative_point()
        ax.text(rp.x, rp.y, f"{dist:.0f} m / L{level}", fontsize=8, ha="center", va="center")

    gpd.GeoSeries([tunnel_geom]).plot(ax=ax, facecolor="steelblue", edgecolor="navy", alpha=0.9)

    ax.set_title("Refinement zones around tunnel (distance from tunnel boundary)")
    ax.set_xlabel("X [m]")
    ax.set_ylabel("Y [m]")
    ax.set_aspect("equal", adjustable="box")
    ax.grid(True, alpha=0.25)
    fig.tight_layout()
    fig.savefig(out_png, dpi=220)
    plt.close(fig)

    return out_png


def plot_gridgen_result_pyvista(cfg: TunnelGridConfig) -> Path | None:
    """Plot final quadtree grid in PyVista with visible cell edges."""
    vtu_path = cfg.gridgen_workspace / "qtg_sv.vtu"
    if not vtu_path.exists():
        vtu_path = cfg.gridgen_workspace / "qtg.vtu"
    if not vtu_path.exists():
        return None

    grid = pv.read(str(vtu_path))
    surface = grid.extract_surface(algorithm="dataset_surface")

    out_png = None
    if cfg.save_pyvista_screenshot:
        cfg.images_dir.mkdir(parents=True, exist_ok=True)
        out_png = cfg.images_dir / "conceptm_gridgen_mesh_pyvista.png"
        p_save = pv.Plotter(off_screen=True)
        p_save.add_mesh(
            surface,
            color="lightsteelblue",
            show_edges=True,
            edge_color="black",
            line_width=0.35,
            opacity=1.0,
        )
        p_save.add_axes()
        p_save.view_isometric()
        p_save.show(screenshot=str(out_png))
        p_save.close()

    if cfg.show_pyvista_interactive:
        p = pv.Plotter()
        p.add_mesh(
            surface,
            color="lightsteelblue",
            show_edges=True,
            edge_color="black",
            line_width=0.35,
            opacity=1.0,
        )
        p.add_axes()
        p.view_isometric()
        p.show(title="Gridgen quadtree mesh (PyVista)")

    return out_png


def plot_simulation_results(cfg: TunnelGridConfig, gwf: flopy.mf6.ModflowGwf) -> None:
    """Build PyVista grid with results and plot head, initial conditions, and k-values."""
    vtk = Vtk(model=gwf, binary=False, smooth=False)
    vtk.add_model(gwf)
    grid = vtk.to_pyvista()

    # Read head file
    head_file = cfg.sim_workspace / f"{cfg.sim_name}.hds"
    if not head_file.exists():
        print(f"Head file not found: {head_file}. Skipped result plotting.")
        return

    hds = flopy.utils.binaryfile.HeadFile(str(head_file))
    h = hds.get_data(kstpkper=(0, 0))

    # Add datasets to grid
    grid["head"] = h.flatten()
    grid["k"] = gwf.npf.k.array.flatten()
    grid["k33"] = gwf.npf.k33.array.flatten()

    # Create boundary indicator array: -1 for CHD cells
    ncpl = int(gwf.modelgrid.nnodes / cfg.nlay)
    ibd = np.ones((cfg.nlay, ncpl), dtype=int)
    if gwf.chd is not None:
        chd_data = gwf.chd.stress_period_data.get_data(key=0)
        if chd_data is not None:
            for lay, icpl in chd_data["cellid"]:
                ibd[lay, icpl] = -1
    grid["boundary"] = ibd.flatten()

    # Plot results
    scalars_list = ["head", "k", "k33", "boundary"]
    cmaps_list = ["viridis", "plasma", "plasma", "coolwarm"]

    for scalar_name, cmap in zip(scalars_list, cmaps_list):
        p = pv.Plotter()
        p.add_mesh(
            grid, scalars=scalar_name, cmap=cmap, show_edges=False, opacity=1.0
        )
        p.add_axes()
        p.show(title=f"Tunnel-refined grid: {scalar_name}")


def build_flopy_disv_model(cfg: TunnelGridConfig, gridprops: dict) -> tuple[flopy.mf6.MFSimulation, flopy.mf6.ModflowGwf]:
    cfg.sim_workspace.mkdir(parents=True, exist_ok=True)

    mf6_exe = resolve_gridgen_executable("mf6")
    sim = flopy.mf6.MFSimulation(
        sim_name=cfg.sim_name,
        sim_ws=str(cfg.sim_workspace),
        exe_name=mf6_exe,
    )
    flopy.mf6.ModflowTdis(sim, time_units="DAYS", nper=1, perioddata=[(1.0, 1, 1.0)])
    flopy.mf6.ModflowIms(sim, complexity="SIMPLE")

    gwf = flopy.mf6.ModflowGwf(sim, modelname=cfg.sim_name, save_flows=True)
    flopy.mf6.ModflowGwfdisv(gwf, pname="disv", **gridprops)

    flopy.mf6.ModflowGwfic(gwf, strt=50.0)
    flopy.mf6.ModflowGwfnpf(
        gwf,
        icelltype=0,
        k=10.0,
        k33=10.0,
        save_specific_discharge=True,
    )

    # Create simple left-right CHD boundary based on x center in DISV cells.
    xc = np.asarray(gwf.modelgrid.xcellcenters).ravel()
    ncpl = int(gridprops["ncpl"])
    chd_spd = []
    for icpl in range(ncpl):
        on_left = xc[icpl] <= cfg.delr
        on_right = xc[icpl] >= (cfg.x_len - cfg.delr)
        if on_left or on_right:
            for lay in range(cfg.nlay):
                if on_left:
                    chd_spd.append(((lay, icpl), 100.0))
                if on_right:
                    chd_spd.append(((lay, icpl), 90.0))

    if chd_spd:
        flopy.mf6.ModflowGwfchd(gwf, stress_period_data=chd_spd)

    flopy.mf6.ModflowGwfoc(
        gwf,
        head_filerecord=[f"{cfg.sim_name}.hds"],
        budget_filerecord=[f"{cfg.sim_name}.cbb"],
        saverecord=[("HEAD", "ALL"), ("BUDGET", "ALL")],
    )

    return sim, gwf


def main() -> None:
    cfg = TunnelGridConfig()
    tunnel_geom = load_tunnel_geometry(cfg)
    depth_m, radius_m = load_tunnel_metadata(cfg)

    print("Building tunnel-focused Gridgen refinement...")
    print(f"Tunnel shapefile: {cfg.tunnel_path}")
    print(f"Tunnel depth/radius: {depth_m:.1f} m / {radius_m:.1f} m")
    print("Refined layers (DISV constraint): all layers")
    print("Refinement zones (distance m -> level):")
    for d, l in zip(cfg.refinement_distances_m, cfg.refinement_levels):
        print(f"  {d:>5.1f} m -> level {l}")

    if cfg.plot_refinement_zones_2d:
        zones_png = plot_refinement_setup(cfg, tunnel_geom)
        print(f"Saved refinement-zone plot: {zones_png}")

    gridprops = build_refined_gridprops(cfg)
    mesh_png = plot_gridgen_result_pyvista(cfg)
    if mesh_png is not None:
        print(f"Saved grid-mesh plot: {mesh_png}")
        if not cfg.show_pyvista_interactive:
            print("Set show_pyvista_interactive=True in TunnelGridConfig for interactive PyVista window.")
    else:
        print("Grid mesh VTU file not found, skipped PyVista mesh plot.")

    sim, gwf = build_flopy_disv_model(cfg, gridprops)
    sim.write_simulation()

    print("\nRunning MODFLOW 6 simulation...")
    success, buff = sim.run_simulation(silent=False, report=False)
    if not success:
        print(f"Simulation failed. Output: {buff}")
    else:
        print("Simulation completed successfully.")
        print("\nPlotting results...")
        plot_simulation_results(cfg, gwf)

    print("\nDone.")
    print(f"DISV cells per layer (ncpl): {gridprops['ncpl']}")
    print(f"Number of vertices (nvert): {gridprops['nvert']}")
    print(f"Gridgen workspace: {cfg.gridgen_workspace}")
    print(f"Simulation workspace: {cfg.sim_workspace}")


if __name__ == "__main__":
    main()
